### ISSUE TITLE
Create an example using spec in multiple files

### ISSUE THREAD

**Issue by camilamaia** [scanapi/examples#1]
Create an example using spec in multiple files.

Current, we only have examples where the specification is only in a single file `api.yaml`. It would be nice to have one example with multiple files specification:

### API specification in multiple files

With `!include`, it is possible to build your API specification in multiple files.

For example, these two files

```yaml
# api.yaml
api:
  endpoints:
    - name: scanapi-demo
      path: ${BASE_URL}
      requests: !include include.yaml
```

```yaml
# include.yaml
- name: health
  path: /health/
```

would generate:

```yaml
api:
  endpoints:
    - name: scanapi-demo
      path: ${BASE_URL}
      requests:
        - name: health
          path: /health/
```
